services:
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: pokey-dynamodb
    ports:
      - '8000:8000'
    command: '-jar DynamoDBLocal.jar -sharedDb -inMemory'
    restart: unless-stopped
